DRAW_FUSIONS ?= $(HOME)/share/env/arriba-2.0.0/opt/arriba_v2.0.0/draw_fusions.R
ANNOTATION_GTF ?= $(HOME)/share/env/arriba-2.0.0/opt/arriba_v2.0.0/GENCODE19.gtf
ASSEMBLY_FA ?= $(HOME)/share/env/arriba-2.0.0/opt/arriba_v2.0.0/GRCh37viral.fa
BLACKLIST_TSV ?= $(HOME)/share/env/arriba-2.0.0/opt/arriba_v2.0.0/database/blacklist_hg19_hs37d5_GRCh37_v2.0.0.tsv.gz
KNOWN_FUSIONS_TSV ?= $(HOME)/share/env/arriba-2.0.0/opt/arriba_v2.0.0/database/known_fusions_hg19_hs37d5_GRCh37_v2.0.0.tsv.gz
PROTEIN_DOMAINS_GFF3 ?= $(HOME)/share/env/arriba-2.0.0/opt/arriba_v2.0.0/database/protein_domains_hg19_hs37d5_GRCh37_v2.0.0.gff3
CYTOBAND ?= $(HOME)/share/lib/resource_files/arriba/cytobands_hg19_hs37d5_GRCh37_v2.1.0.tsv
STAR_INDEX_DIR ?= $(HOME)/share/lib/resource_files/arriba/STAR_index_GRCh37viral_GENCODE19